"""Updated models with OTP expiry and prediction status

Revision ID: fd4efb0b264f
Revises: 0c913bbaadd3
Create Date: 2024-12-27 23:22:48.385121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd4efb0b264f'
down_revision = '0c913bbaadd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['target_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('target_user_id')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
